version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "buychain-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hly4jrfgbonf"
s3_prefix = "buychain-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
disable_rollback = true

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1e9i8sfxf8cs"
s3_prefix = "test-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []
