AWSTemplateFormatVersion: 2010-09-09
Description: >-
  serverless-tools
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 30

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - demo
      - prod
    Description: Stage name

Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-api
      StageName: !Ref Stage
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt LambdaAuthorizerFunction.Arn

  GeneratePdfLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Serverless Chrome/Puppeteer Layer
      ContentUri: layers/generate-pdf
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x

  LambdaAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/authorizer/
      Handler: authorizer.handler
      Timeout: 60
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayRestApi
            Path: /auth
            Method: get
      Environment:
        Variables:
          MICROSERVICE_AUTHORIZATION_HOST: !Sub '{{resolve:ssm:microservice_auth_host_${Stage}:1}}'
  generatePdf:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/generatePDF
      Handler: generatePdf.handler
      Description: generate pdf
      Timeout: 60
      MemorySize: 512
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pdf
            Method: post
            RestApiId: !Ref ApiGatewayRestApi
      Layers:
        - !Ref GeneratePdfLayer
      Environment:
        Variables:
          MICROSERVICE_DOCUMENTS_HOST: !Sub '{{resolve:ssm:microservice_documents_host_${Stage}:1}}'

  generatePdfSystem:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/generatePDF
      Handler: generatePdfSystem.handler
      Description: generate pdf from system
      Timeout: 60
      MemorySize: 512
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pdf/system
            Method: post
            RestApiId: !Ref ApiGatewayRestApi
      Layers:
        - !Ref GeneratePdfLayer
      Environment:
        Variables:
          MICROSERVICE_DOCUMENTS_HOST: !Sub '{{resolve:ssm:microservice_documents_host_${Stage}:1}}'
Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for stage'
    Value: !Sub 'https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
