AWSTemplateFormatVersion: 2010-09-09
Description: >-
  serverless-tools
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs16.x
    Architectures:
      - x86_64
    MemorySize: 128
    CodeUri: src/lambdas/
    Timeout: 30

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - demo
      - prod
    Description: Stage name

Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-api
      StageName: !Ref Stage
  getPdf:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getPdf.handler
      Description: Get PDF
      Events:
        Api:
          Type: Api
          Properties:
            Path: /get-pdf
            Method: GET
            RestApiId: !Ref ApiGatewayRestApi
Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for stage'
    Value: !Sub 'https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
