version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
  sam: circleci/aws-sam-serverless@4.0.0
commands:
  sam-cli-setup:
    steps:
      - aws-cli/setup
      - sam/install
      - run: npm run build
  sam-deploy:
    parameters:
      stackName:
        default: 'buychain-dev'
        type: string
      stage:
        default: 'dev'
        type: string
    steps:
      - run: sam deploy --stack-name <<parameters.stackName>> --s3-bucket $S3_BUCKET --capabilities CAPABILITY_IAM --region us-east-1 --parameter-overrides Stage=<<parameters.stage>> --no-confirm-changeset --no-fail-on-empty-changeset

jobs:
  lint-test:
    docker:
      - image: 'circleci/node:16'
    steps:
      - checkout
      - run:
          name: Install node packages
          command: npm ci
      - run:
          name: Create layers
          command: cd src/layers/generate-pdf/nodejs/node_modules/pdf && npm ci
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit test
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy-dev:
    executor: sam/default
    steps:
      - attach_workspace:
          at: .
      - sam-cli-setup
      - sam-deploy:
          stackName: 'buychain-dev'
          stage: 'dev'
  deploy-demo:
    executor: sam/default
    steps:
      - attach_workspace:
          at: .
      - sam-cli-setup
      - sam-deploy:
          stackName: 'buychain-demo'
          stage: 'demo'
  deploy-prod:
    executor: sam/default
    steps:
      - attach_workspace:
          at: .
      - sam-cli-setup
      - sam-deploy:
          stackName: 'buychain-prod'
          stage: 'prod'

filter_workflow-jobs: &filter_workflow-jobs
  branches:
    ignore: /.*/
  tags:
    only: /v[0-9]+(\.[0-9]+)+/

workflows:
  buychain-deploy-workflow:
    jobs:
      - lint-test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
      - deploy-dev:
          context: aws-secrets
          name: deploy-dev
          requires:
            - lint-test
          filters:
            branches:
              only: develop
      - deploy-demo:
          context: aws-secrets
          name: deploy-demo
          requires:
            - lint-test
          filters:
            <<: *filter_workflow-jobs
      - hold-deploy-prod:
          type: approval
          requires:
            - deploy-demo
          filters:
            <<: *filter_workflow-jobs
      - deploy-prod:
          context: aws-secrets
          name: deploy-prod
          filters:
            <<: *filter_workflow-jobs
          requires:
            - hold-deploy-prod
